version: "2.24.6"

services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: 1234
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-cluster:rocky8
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - slurm_jobdir:/data
      - etc_munge:/etc/munge
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-cluster:rocky8
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - slurm_jobdir:/data
      - etc_munge:/etc/munge
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  node1:
    image: slurm-cluster:rocky8
    hostname: node1
    container_name: node1
    volumes:
      - slurm_jobdir:/data
      - etc_munge:/etc/munge
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  node2:
    image: slurm-cluster:rocky8
    hostname: node2
    container_name: node2
    volumes:
      - slurm_jobdir:/data
      - etc_munge:/etc/munge
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  slurm_jobdir:
  var_lib_mysql:
